name: Resize images

on: 
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  build:
    name: Image Resizer Inplace Limit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: petems/img-resizer-inplace@965e3bde3779ca4af2fb78b5e5334cb399f5b019
        with:
          target: # default is images
          # New resolution for images
          dimensions: # default is 70%
          widthLimit: 1024 
          heightLimit: 768
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Action Bot
          author_email: github-action[bot]@github.com
          message: "Resizing imges with img-resizer-inplace-limit"